# Generated by Django 3.2.14 on 2022-08-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220822_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_grind',
            new_name='is_bean',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_roast',
        ),
    ]
